-- Seeder Pengaturan Website: Gampong Munye Pirak
-- Jalankan di phpMyAdmin InfinityFree pada database tujuan Anda

INSERT INTO `pengaturan` (`nama_setting`, `nilai_setting`, `keterangan`) VALUES
('website_nama', 'Website Resmi Gampong Munye Pirak', 'Nama website'),
('website_deskripsi', 'Gampong Munye Pirak adalah sebuah gampong di Kabupaten Aceh Utara, Provinsi Aceh.', 'Deskripsi website'),
('website_keywords', 'gampong munye pirak, meunye pirak, aceh utara, provinsi aceh, pemerintah gampong', 'Keywords website'),
('social_facebook', '', 'Link Facebook'),
('social_instagram', '', 'Link Instagram'),
('social_youtube', '', 'Link YouTube'),
('whatsapp_number', '', 'Nomor WhatsApp'),
('office_hours_text', 'Senin - Jumat, 08.00 - 16.00 WIB', 'Jam operasional footer'),
('footer_brand_description', 'Portal informasi resmi Gampong Munye Pirak, Kabupaten Aceh Utara, Provinsi Aceh.', 'Deskripsi footer'),
('footer_badge_text', 'Website Resmi Pemerintah Gampong', 'Teks badge footer'),
('privacy_policy_label', 'Kebijakan Privasi', 'Label link kebijakan privasi'),
('privacy_policy_url', '/kontak', 'URL kebijakan privasi'),
('menu_profile_label', 'Profil Gampong', 'Label menu profil'),
('menu_story_label', 'Sejarah Gampong', 'Label menu cerita/sejarah'),
('menu_vision_label', 'Visi & Misi', 'Label menu visi misi'),
('menu_structure_label', 'Struktur Organisasi', 'Label menu struktur'),
('contact_hero_title', 'Hubungi Pemerintah Gampong Munye Pirak', 'Judul hero kontak'),
('contact_hero_description', 'Sampaikan pertanyaan, usulan, atau kebutuhan layanan administrasi melalui kanal resmi Gampong Munye Pirak.', 'Deskripsi hero kontak'),
('login_visual_title', 'Pusat Administrasi Digital Gampong Munye Pirak', 'Judul visual login'),
('login_form_description', 'Silakan masuk menggunakan akun resmi pengelola website Gampong Munye Pirak.', 'Deskripsi form login'),
('hero_explore_label', 'Jelajahi Gampong', 'Label tombol hero'),
('home_services_title', 'Layanan Unggulan Gampong', 'Judul layanan beranda'),
('home_services_subtitle', 'Pelayanan publik Gampong Munye Pirak untuk kebutuhan administrasi, informasi, dan aspirasi masyarakat.', 'Subjudul layanan beranda'),
('home_vision_title', 'Visi & Misi Gampong', 'Judul visi misi beranda'),
('home_vision_subtitle', 'Arah pembangunan Gampong Munye Pirak untuk kemajuan masyarakat dan tata kelola pemerintahan yang baik.', 'Subjudul visi misi beranda'),
('home_news_title', 'Berita Terbaru', 'Judul berita beranda'),
('home_news_subtitle', 'Informasi kegiatan dan program Gampong Munye Pirak.', 'Subjudul berita beranda'),
('home_gallery_title', 'Galeri Kegiatan', 'Judul galeri beranda'),
('home_gallery_subtitle', 'Dokumentasi kegiatan masyarakat dan pemerintahan Gampong Munye Pirak.', 'Subjudul galeri beranda'),
('home_stats_title', 'Statistik Gampong Munye Pirak', 'Judul statistik beranda'),
('home_stats_subtitle', 'Data ringkas kondisi dan perkembangan Gampong Munye Pirak.', 'Subjudul statistik beranda'),
('news_page_title', 'Kabar Terbaru Gampong Munye Pirak', 'Judul halaman berita'),
('news_page_description', 'Berita resmi seputar kegiatan masyarakat dan pemerintahan Gampong Munye Pirak.', 'Deskripsi halaman berita'),
('gallery_page_description', 'Galeri dokumentasi kegiatan Gampong Munye Pirak.', 'Deskripsi halaman galeri'),
('profile_empty_history_text', 'Data sejarah gampong belum diisi.', 'Teks kosong sejarah'),
('profile_info_title', 'Info Gampong', 'Judul kotak info profil'),
('vision_page_description', 'Visi dan misi pembangunan Gampong Munye Pirak.', 'Deskripsi halaman visi misi'),
('vision_empty_text', 'Visi gampong belum diisi.', 'Teks kosong visi'),
('mission_empty_text', 'Misi gampong belum diisi.', 'Teks kosong misi'),
('structure_page_description', 'Susunan perangkat pemerintahan Gampong Munye Pirak.', 'Deskripsi halaman struktur'),
('structure_section_title', 'Bagan Struktur Organisasi Gampong Munye Pirak', 'Judul section struktur'),
('structure_image_alt', 'Bagan struktur organisasi Gampong Munye Pirak', 'Alt gambar struktur'),
('structure_leader_subtitle', 'Pimpinan Pemerintahan Gampong', 'Subjudul leader struktur'),
('structure_leader_description', 'Memimpin kebijakan, pelayanan, dan pembangunan gampong bersama perangkat desa.', 'Deskripsi leader struktur'),
('structure_empty_text', 'Struktur organisasi gampong belum diisi.', 'Teks kosong struktur'),
('service_item_1_title', 'Administrasi Surat', 'Judul layanan 1'),
('service_item_1_desc', 'Pelayanan surat pengantar dan administrasi dasar untuk warga.', 'Deskripsi layanan 1'),
('service_item_1_icon', 'dokumen', 'Icon layanan 1'),
('service_item_2_title', 'Informasi Pemerintahan', 'Judul layanan 2'),
('service_item_2_desc', 'Publikasi informasi program, agenda, dan pengumuman resmi gampong.', 'Deskripsi layanan 2'),
('service_item_2_icon', 'informasi', 'Icon layanan 2'),
('service_item_3_title', 'Aspirasi Masyarakat', 'Judul layanan 3'),
('service_item_3_desc', 'Saluran aspirasi, saran, dan pertanyaan masyarakat Gampong Munye Pirak.', 'Deskripsi layanan 3'),
('service_item_3_icon', 'kontak', 'Icon layanan 3'),
('service_item_4_title', 'Dokumentasi Kegiatan', 'Judul layanan 4'),
('service_item_4_desc', 'Dokumentasi kegiatan pemerintahan dan masyarakat dalam galeri gampong.', 'Deskripsi layanan 4'),
('service_item_4_icon', 'galeri', 'Icon layanan 4'),
('important_announcement_active', '0', 'Aktifkan banner pengumuman penting'),
('important_announcement_text', '', 'Isi pengumuman penting'),
('important_announcement_link', '', 'Link pengumuman penting'),
('quick_location_url', 'https://www.google.com/maps/search/?api=1&query=Meunye+Pirak+Matangkuli+Aceh+Utara', 'URL lokasi kantor desa'),
('map_section_title', 'Lokasi Gampong Munye Pirak', 'Judul section peta'),
('map_section_description', 'Gampong Munye Pirak berada di Kabupaten Aceh Utara, Provinsi Aceh.', 'Deskripsi section peta'),
('map_embed_url', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11509.520611549646!2d97.25856884477145!3d5.020577241517464!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3047881d4767f301%3A0x5a2be2c6bc634560!2sMeunye%20Pirak%2C%20Kec.%20Matangkuli%2C%20Kabupaten%20Aceh%20Utara%2C%20Aceh!5e1!3m2!1sid!2sid!4v1775194035986!5m2!1sid!2sid', 'Link embed Google Maps'),
('popular_service_1_label', 'Surat Pengantar', 'Label layanan populer 1'),
('popular_service_1_url', '/kontak', 'URL layanan populer 1'),
('popular_service_1_icon', 'dokumen', 'Icon layanan populer 1'),
('popular_service_2_label', 'Kontak Gampong', 'Label layanan populer 2'),
('popular_service_2_url', '/kontak', 'URL layanan populer 2'),
('popular_service_2_icon', 'telepon', 'Icon layanan populer 2'),
('popular_service_3_label', 'Berita Gampong', 'Label layanan populer 3'),
('popular_service_3_url', '/berita', 'URL layanan populer 3'),
('popular_service_3_icon', 'berita', 'Icon layanan populer 3'),
('popular_service_4_label', 'Galeri Kegiatan', 'Label layanan populer 4'),
('popular_service_4_url', '/galeri', 'URL layanan populer 4'),
('popular_service_4_icon', 'galeri', 'Icon layanan populer 4')
ON DUPLICATE KEY UPDATE
`nilai_setting` = VALUES(`nilai_setting`),
`keterangan` = VALUES(`keterangan`);

UPDATE `profil_desa`
SET
  `nama_desa` = 'Munye Pirak',
  `alamat` = 'Gampong Munye Pirak, Kec. Matangkuli, Kabupaten Aceh Utara, Provinsi Aceh',
  `telepon` = '',
  `email` = '',
  `sejarah` = '<p>Gampong Munye Pirak merupakan salah satu gampong di Kecamatan Matangkuli, Kabupaten Aceh Utara, Provinsi Aceh. Dalam bahasa Aceh, desa disebut sebagai gampong. Kehidupan masyarakat Munye Pirak tumbuh dengan nilai kebersamaan, adat, dan gotong royong.</p>',
  `visi_misi` = 'Visi: Terwujudnya Gampong Munye Pirak yang maju, mandiri, berbudaya, dan sejahtera.\nMisi: 1. Meningkatkan kualitas pelayanan publik gampong.\n2. Mendorong tata kelola pemerintahan yang transparan dan akuntabel.\n3. Menguatkan partisipasi masyarakat dalam pembangunan.\n4. Mengembangkan potensi sosial dan ekonomi lokal.',
  `updated_at` = NOW()
WHERE `id` = 1;

INSERT INTO `profil_desa` (`id`, `nama_desa`, `alamat`, `telepon`, `email`, `sejarah`, `visi_misi`, `struktur_organisasi`, `created_at`, `updated_at`)
SELECT 1, 'Munye Pirak', 'Gampong Munye Pirak, Kec. Matangkuli, Kabupaten Aceh Utara, Provinsi Aceh', '', '',
'<p>Gampong Munye Pirak merupakan salah satu gampong di Kecamatan Matangkuli, Kabupaten Aceh Utara, Provinsi Aceh.</p>',
'Visi: Terwujudnya Gampong Munye Pirak yang maju, mandiri, berbudaya, dan sejahtera.\nMisi: 1. Meningkatkan kualitas pelayanan publik gampong.\n2. Mendorong tata kelola pemerintahan yang transparan dan akuntabel.\n3. Menguatkan partisipasi masyarakat dalam pembangunan.\n4. Mengembangkan potensi sosial dan ekonomi lokal.',
'', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `profil_desa` WHERE `id` = 1);
